```js
console.log(1)
setTimeout(()=>{console.log(2)},0)
new Promise((reject)=>{
    console.log(3)
    reject()
}).then(()=>{
    console.log(4)
}).catch(()=>{
    console.log(5)
})
console.log(6)

```

我的答案: 1 3 6 5 2

正确答案: 1 3 6 4 2

**坑点: promise参数 `resolve`的位置上写着`reject`**

